[package]
name = "vovk_hello_world_demo"
version = "0.0.0"
edition = "2021"

[dependencies]
vovk_hello_world = "0.0.56"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
